### PR TITLE
Port password strength indicator

### LINKED ISSUE #72: Password strength indicator missing
**Describe the bug**
In the old Admin UI when creating a new user, you get a password strength indicator, in the new 

Old (Angular JS):
Screenshot 2022-07-11 at 16 18 50

New (Picard):
Screenshot 2022-07-11 at 16 17 00

**To Reproduce**
1. https://picard.vm2.elan.codes/admin-ui/index.html#/users/users
2. Login (admin/opencast)
3. Go to https://picard.vm2.elan.codes/admin-ui/index.html#/users/users
4. Click + Add User

### PR DESCRIPTION
**Pull request by Arnei**
Reintroduces the password strenght indicator from the old admin ui by porting the code from the original PR: https://github.com/opencast/opencast/pull/3343

Fixes #72.

### CODE REVIEW

File: src/components/users/partials/wizard/NewUserGeneralTab.tsx [hunk 1]
```diff
@@ -93,10 +93,98 @@ const NewUserGeneralTab = ({
...
+		const strength = Math.max(1, usedRules + uniqueChars + password_length + lowerCase + upperCase + number + symbol);
+		return Math.round(strength);
+	}
+
+	const setProgBar = (strength: number) => {
+		if (strength >= 90) {
+			return ["#388ed6", "USERS.USERS.DETAILS.STRENGTH.VERYSTRONG"]
+		}
+		else if (strength >= 70) {
+			return ["green", "USERS.USERS.DETAILS.STRENGTH.STRONG"]
```
Comment (lkiesow) [inline src/components/users/partials/wizard/NewUserGeneralTab.tsx:154]: Can we maybe switch these colors? As an indicator, red is bad and green is good. Blue is unusual and maybe somewhere in between, but not better. Or maybe have green as very string and a yellow-green as good?

**Review by lkiesow — COMMENTED** [review]
Works well. Only the color for very strong looks a bit odd to me.

File: src/components/users/partials/wizard/NewUserGeneralTab.tsx (hunk 1 above)
Comment (Arnei) [reply src/components/users/partials/wizard/NewUserGeneralTab.tsx]: I have no opinion on this. Switched green and blue for now.

**Review by lkiesow — APPROVED** [review]
