### PR TITLE
fix formik metadata reference according to new scheme

### LINKED ISSUE #1518: Series ACL not copied in New Event Wizard
In the add event wizard, if a series is selected in the metadata tab, the respective ACL is copied to the new event and it's automatically set and visible in the ACL tab. The bug consists in that the above expected behaviour is broken (the series ACL does not get copied to the event ACL).

It is assumed that this unintended behaviour was introduced with https://github.com/opencast/opencast-admin-interface/commit/25b77adaa0cefdbb9b8869f88b86dfa6b80b9946

### PR DESCRIPTION
**Pull request by ypatios**
Fixes #1518 

"In the add event wizard, if a series is selected in the metadata tab, the respective ACL is copied to the new event and it's automatically set and visible in the ACL tab. The bug consists in that the above expected behaviour is broken (the series ACL does not get copied to the event ACL).

"It is assumed that this unintended behaviour was introduced with https://github.com/opencast/opencast-admin-interface/commit/25b77adaa0cefdbb9b8869f88b86dfa6b80b9946"

grok.com (v4.1, Expert Mode) has helped with analysis and coding.

### CODE REVIEW

**Review by Arnei — APPROVED** [review]
Urg, my changes were supposed to make these things happen less, not more :(

Anyway, this looks reasonable, thanks for fixing! I changed to the base to `r/19.x` as we surely want it in there, could you rebase on that?

**Comment by ypatios** [comment]
thx @Arnei :) did the rebase; all looking clean. @gregorydlogan, the ~48 irrelevant commits gone ;)
lmk if all good for merging.

File: src/components/events/partials/ModalTabsAndPages/NewAccessPage.tsx [hunk 1]
```diff
@@ -24,10 +24,13 @@ import ModalContentTable from "../../../shared/modals/ModalContentTable";
  * This component renders the access page for new events and series in the wizards.
  */
 interface RequiredFormProps {
-	"dublincore/episode_isPartOf": string,
-	policies: TransformedAcl[],
-	aclTemplate: string,
-	// theme: string,
+  metadata: {
+    "dublincore/episode_isPartOf": string,
+    // other metadata fields as needed
```
Comment (geichelberger) [inline src/components/events/partials/ModalTabsAndPages/NewAccessPage.tsx]: The comment should be removed.

Comment (ypatios) [reply src/components/events/partials/ModalTabsAndPages/NewAccessPage.tsx]: fair point :) done
