### PR TITLE
Fix style of saved filter sets

### LINKED ISSUE #809: Extremely poor contrast on stored filter button
Screenshot from 2024-07-03 23-14-15

### LINKED ISSUE #811: Broken alignment of icons in stored filter menu
The menu for stored filters does not have a proper alignment of its elements. It should probably look and act more like a small table.

Screenshot from 2024-07-03 23-16-21

### PR DESCRIPTION
**Pull request by dennis531**
Changes:
- Fix class name
- Use flex box
- Allow arbitrary word breaks

Close #811, close #809

### CODE REVIEW

**Review by lkiesow — APPROVED** [review]
Way better than before :rocket:

File: src/components/shared/TableFilterProfiles.tsx [hunk 1]
```diff
@@ -168,7 +168,7 @@ const TableFiltersProfiles = ({
 											<Tooltip title="profile.description">
 												<button
 													onClick={() => chooseFilterProfile(profile.filterMap)}
-                        className="button-li	ke-anchor"
+                        	className="button-like-anchor"
```
Comment (lkiesow) [inline src/components/shared/TableFilterProfiles.tsx:171]: Indentation still doesn't seem to be correct here

Comment (dennis531) [reply src/components/shared/TableFilterProfiles.tsx]: There was a mix of spaces and tabs. Now it should be tabs only. I would prefer to use spaces instead of tabs in general.

**Review by lkiesow — APPROVED** [review]
