### PR TITLE
Fix video preview displaying wrong video

### LINKED ISSUE #466: Admin interface displays media preview from different events
It is very good to have a preview in the media details:

Bildschirmfoto 2024-05-25 um 09 33 08

But if you look at the preview from another video, there is the preview from the last video:

Bildschirmfoto 2024-05-25 um 09 33 42

### PR DESCRIPTION
**Pull request by Arnei**
The video preview player in the event assets details would try to display the media from the assets previously visited, which would lead to the player displaying no or the wrong video. This fixes that by ensuring that the player reloads when the url changes.

Fixes #466.

### CODE REVIEW

File: src/components/events/partials/ModalTabsAndPages/EventDetailsAssetMediaDetails.tsx [hunk 1]
```diff
@@ -366,8 +374,8 @@ const EventDetailsAssetMediaDetails = ({
 								{/* video player */}
 								<div className="video-player">
 									<div>
-										<video id="player" controls>
-											<source src={media.url} type="video/mp4" />
+										<video ref={videoRef} id="player" controls>
```
Comment (lkiesow) [inline src/components/events/partials/ModalTabsAndPages/EventDetailsAssetMediaDetails.tsx:377]: This also displays for subtitle or audio tracks. Maybe we can do something like:
- if `media.has_video` → `<video …`
- else if `media.has_audio` → `<audio …`
- else hide this section

**Review by lkiesow — CHANGES_REQUESTED** [review]
Looks good in general. I'm not sure if the mime type is needed. Testing this locally, videos do not work for me in either Firefox or Chromium. But that may also be caused by them being loaded from develop directly?

File: src/components/events/partials/ModalTabsAndPages/EventDetailsAssetMediaDetails.tsx [hunk 2]
```diff
@@ -366,8 +374,8 @@ const EventDetailsAssetMediaDetails = ({
 								{/* video player */}
 								<div className="video-player">
 									<div>
-										<video id="player" controls>
-											<source src={media.url} type="video/mp4" />
```
[the remark this answers is not in the document]
Comment (Arnei) [reply src/components/events/partials/ModalTabsAndPages/EventDetailsAssetMediaDetails.tsx:370]: Good catch, thanks.

File: src/components/events/partials/ModalTabsAndPages/EventDetailsAssetMediaDetails.tsx (hunk 1 above)
Comment (Arnei) [reply src/components/events/partials/ModalTabsAndPages/EventDetailsAssetMediaDetails.tsx:377]: Reasonable, but I would leave that for a different PR. This is just about loading the correct media file at all.
