### PR TITLE
make cancel buttons work for users/groups/access

### LINKED ISSUE #1182: Cancel button not working while editing User/Groups/Access policies tab
When trying to edit user, groups or access policies details. The cancel button on the wizard in not working. 

Refer below screenshot:

Image

### PR DESCRIPTION
**Pull request by ppettit**
Fixes #1182 

Just makes the cancel button close the modal which is the behaviour of the old admin UI

### CODE REVIEW

**Comment by Arnei** [comment]
Supercedes #1204 I suppose?

File: src/components/users/partials/modal/GroupDetails.tsx [hunk 1]
```diff
@@ -98,6 +98,7 @@ const GroupDetails: React.FC<{
 						{/* Navigation buttons and validation */}
 						<WizardNavigationButtons
 							formik={formik}
+							previousPage={() => close()}
```
Comment (Arnei) [inline src/components/users/partials/modal/GroupDetails.tsx:101]: Can be simplified to (in all three instances):

```suggestion
							previousPage={close}
```

**Review by Arnei — CHANGES_REQUESTED** [review]
Works and makes sense to me. Small suggestion below

File: src/components/users/partials/modal/GroupDetails.tsx (hunk 1 above)
Comment (ppettit) [reply src/components/users/partials/modal/GroupDetails.tsx]: done, i had copied and pasted from elsewhere in the code :wink:

**Comment by ppettit** [comment]
> Supercedes #1204 I suppose?

yes, sorry that as not linked to the issue so i didn't find it. seems like a lot of unrelated changes in that PR too

**Review by Arnei — APPROVED** [review]
